- name: DNS
  hosts: all
  sudo: true
  tasks:
  - name: Install logwatch
    yum: name=logwatch state=latest
  - name: Paste config
    template: >
      src=templates/logwatch.conf
      dest=/usr/share/logwatch/default.conf/logwatch.conf
